### ISSUE TITLE
Increase number of UP boxes to at least 6 on emilia

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#117]
(This work will probably be done directly in the master branch.)

Deploy additional OPQ Boxes. This means:

* Get at least three additional OPQ Boxes ready for deployment.
* Communicate with Dan Port (dport@hawaii.edu) and Miles Topping (mtopping@hawaii.edu) to establish locations for new boxes. They are awaiting contact from a student to arrange delivery and setup.
* Edit opq/view/config/settings.development.json to define: (1) location entities for the new boxes, (2) the boxes (id, calibration_constant, location, etc.) and (3) users (dport@hawaii.edu and mtopping@hawaii.edu). 
* Redeploy view with new settings.development.json to define these boxes on emilia. 
* Update health's config file with new box IDs.
* Plug in boxes and verify that they are sending data.

**Comment by philipmjohnson** [comment]
We have approval to put an OPQ box in the basement of hamilton in the LIS space. As you enter the commons area, to the left of the 3F classroom is a hallway, and on the other side of the hallway there is a bookshelf on top of which is a charging station next to some outlets. We can use an outlet.  We need to put a sign on top explaining a little bit about what this is and maybe pointing them to the OPQ.org website for more details.  I think there is a poster with READ in large caps over the bookshelf as well.

**Comment by anthonyjchriste** [comment]
6 devices up with number 7 on its way. If we could get device 4 to become active, it'd be a beautiful thing.
