### ISSUE TITLE
Fix bug in Measurement document insertion

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#127]
Please do work for this task in a branch called issue-127.

Currently, live data for boxes is broken and today's count for Measurement data is zero. This appears to be because the timestamps for new Measurements are a day or so off. 

The rest of us believe this is a bug in Makai. 😸

**Comment by sergey-negrashov** [comment]
After some digging I narrowed down this issue to the mongo insertion for measurements. Instead of inserting every measurement separately, I now batch in windows of 1 second. This seemed to have resolved the issue.

**Comment by philipmjohnson** [comment]
Excellent!  I wonder if the Rust people can be easily notified that their Mongo driver falls apart under load?
