### ISSUE TITLE
Add high fidelity frequency measurements to Mauka

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#132]
Please perform work for this task in branch issue-132.

This task involves modifying the MakaiEventPlugin to calculate high-fidelity frequency measurements from the raw waveform from an OPQ Box.

1. Read through the OPQ Mauka Developer Guide: https://openpowerquality.org/docs/developerguide-mauka.html and prepare your development environment.

2. Familiarize yourself with the [numpy](http://www.numpy.org/) and [scipy](https://www.scipy.org/) libraries.

3. Modify opq/mauka/plugins/MakaiEventPlugin.py to convert the provided waveform into a list of frequency measurements.

4. Each frequency measurement should use a window length of a single electrical cycle

5. Once the frequency calculation is complete, produce a message to the Mauka system with a topic of "Frequencies" and a pickled payload consisting of (box_event, box_id, and frequencies array.)

6. Attempt to perform all calculations using numpy. The resulting frequency array should also be a numpy array.

7. Test your code on OPQ Sim by deploying succesfully deploying Mauka to OPQ Sim, generating frequency events on OPQ Sim, and monitoring the expected Mauka messages.

8. Have your code reviewed before merging into master.

**Comment by philipmjohnson** [comment]
As of 30 seconds ago, the location of the OPQ Mauka Developer Guide is https://openpowerquality.org/docs/cloud-mauka.html#development 😄
