### ISSUE TITLE
Implement a Mauka plugin that classifies IEEE 1159 Voltage Events

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#135]
Please perform work for this task in branch issue-135.

This task involves creating a new plugin that classifies events according to IEEE 1159.

1. Read through the OPQ Mauka Developer Guide:https://openpowerquality.org/docs/cloud-mauka.html#development and prepare your development environment.

2. Familiarize yourself with the [numpy](http://www.numpy.org/) and [scipy](https://www.scipy.org/) libraries.

3. Create a new plugin at opq/mauka/Ieee1159Plugin.py

4. Subscribe to the "VrmsWaveform" topic.

5. When the plugin receives data, go through the high fidelity Vrms waveform and classify the following event types:
 * Instantaneous dip
 * Momentary dip
 * Temporary dip
 * Instantaneous swell
 * Momentary swell
 * Temporary swell
 * Overvoltage 
 * Undervoltage 
 * Interruption

6. When classified events are found, create a new anomaly document for each event and store it to the anomalies collection. You may need to modify opq/mauka/mongo.py to add new event types and new collections types.

7. Test your code on OPQ Sim by deploying successfully deploying Mauka to OPQ Sim, generating voltage events on OPQ Sim, and monitoring the expected Mauka messages.

7. Have your code reviewed before merging into master.

**Comment by philipmjohnson** [comment]
Note that it's IEEE 1159, not IEEE 1156.  Please update any references in the code appropriately. Sorry for the typo.
