### ISSUE TITLE
Implement a plugin that detects IEEE 1159 Frequency Variations

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#147]
Please do work for this task in a branch called issue-147.

Implement a Mauka plugin that detects, classifies, and stores frequency variation incidents. 

Frequency variations should be classified as +/- 0.10hz as specified in page 7 of the IEEE standard.

The new plugin should subscribe to the high fidelity frequency array created produced by the MakaiEventPlugin.

**Comment by dickensc** [comment]
Thousands of incidents for single event, furthermore, at the moment the fitting method is very computationally expensive.

Revisit to lower sensitivity and join multiple events and improve performance.
