### ISSUE TITLE
Integrated, or integrate with, energy monitoring (feature request)

### ISSUE THREAD

**Issue by ptr727** [openpowerquality/opq#161]
It would be fantastic if you could collaborate with the open energy monitoring community at Open Energy Monitor, and incorporate power quality and energy monitoring in a single hardware solution, that can be mounted in or near the panel, and monitor both supply legs.

Please see this thread where I asked for the same:
https://community.openenergymonitor.org/t/power-quality-monitor/8124

To take it further, think of an open source version of products like https://sense.com/ that is an A/D and math and AI and ML. I imagine the unit in my panel collecting data, doing some compression or FFT or sampling or thresholding, and sending it to AWS or Azure, where we can do all sorts of interesting things with the data.

**Comment by philipmjohnson** [comment]
This is an interesting idea!  To avoid duplication of discussion, let's close this issue and use the thread you started on the OEM side (https://community.openenergymonitor.org/t/power-quality-monitor/8124). I've replied over there.
