### ISSUE TITLE
Determine why Health is reporting that Makai is going up and down

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#162]
Please do work for this task in a branch called issue-161.

Either the Health Module does not appear to be set up correctly, or Makai is going up and down:

<img width="707" alt="screen shot 2018-08-04 at 7 59 29 am" src="https://user-images.githubusercontent.com/290288/43679180-93b31664-97bc-11e8-9b57-277f25f72373.png">

We need to look into this and figure out why it's happening.

**Comment by anthonyjchriste** [comment]
The logs show Makai but slack and this issue say Mauka. Please confirm which you are seeing issues with.

**Comment by philipmjohnson** [comment]
Whoops fixed.

**Comment by philipmjohnson** [comment]
Evan redeployed Health on 9/4/18, and so far it appears that Health is correctly reporting Makai to be up all the time. 

The way Health checks makai is as follows:  Health publishes an event to Makai, and then asks Makai to retrieve an event. We think it was going up and down because right after getting the event from Makai, Health tries to get the event from Mongo, and it's not there.  If that occurs, Health writes Down with "" (now will say down with Mongo). 

So, if the problem reappears, we suggest that the thread should sleep for a couple of seconds before querying Mongo for the event.
