### ISSUE TITLE
Design documentation

### ISSUE THREAD

**Issue by ptr727** [openpowerquality/opq#163]
Hi, could you please produce, post, or point me to your design documentation?
E.g. design reasoning, component selection reasoning, component value calculation, etc.

Something like this:
https://www.switchcraft.org/project-blog/2016/12/11/designing-a-voltage-sensing-pcb

Thank you

**Comment by philipmjohnson** [comment]
The hardware design documentation is available here:

https://openpowerquality.org/docs/box-hardware-design.html

**Comment by davidrb** [comment]
You can also find schematics for the PCB here https://github.com/openpowerquality/opq/blob/master/box/Schematics/v3/opqbox3.pdf.

**Comment by ptr727** [comment]
Thank you
