### ISSUE TITLE
Move Makai to new protocol

### ISSUE THREAD

**Issue by sergey-negrashov** [openpowerquality/opq#168]
Please do work for this task in a branch called issue-168.

This task involves moving the Makai codebase to operate on the new protocol. The new protocol is described in the [protocol](https://github.com/openpowerquality/opq/blob/master/protocol/opqbox3.proto) folder. This change comes with the additional caveat, that the Acquisition broker no longer manages event storage, and this task now falls on Makai.

Please add task checklist here.
**Housekeeping:**

- [ ] Move the shared library to one crate with the binary. See 144 for details
- [ ] Include the new protobuf file in the  build process.
- [ ] Change the interface for the plugin type to use new protocol data types.

**Development:**

- [ ] Change the capture methods.
- [ ] Change the trends methods.
- [ ] Change the Raw waveform interface.

**Testing:**

- [ ] Create a simple boilerplate for plugin (printplugin)
- [ ] Create a simple boilerplate for triggering (triggeringplugin)

**TBD:**

- Health interface.
- Documentation.

**Comment by philipmjohnson** [comment]
Can you please rename the branch containing this work from '168' to 'issue-168' for consistency with the other branch names?
