### ISSUE TITLE
Improve Location Manager Lat/Long specification

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#169]
Please do work for this task in a branch called issue-169.

Here is a screenshot of the current UI for the Location Manager page:

<img width="724" alt="screen shot 2018-09-12 at 7 22 33 am" src="https://user-images.githubusercontent.com/290288/45442098-c1d4df00-b65c-11e8-8c9b-8fc179dcd4d8.png">

The current UI has several problems:

* The fields where the user enters latitude and longitude are marked as "coordinates". It is not clear whether you specify latitude first or longitude first. To fix this, the field where the user enters latitude should be clearly marked as latitude, and the field whether the user enters longitude should be clearly marked as longitude.

* As shown in the screen shot, the UI makes it appear as if you can enter more than two coordinates for a given location.  That should not be possible.

* Note that legal latitude is -90 to +90, and legal latitude is -180 to +180. Be sure to check that.

* Finally, there is no feedback in the UI as to whether the coordinates specify the intended location. To fix this, implement a mechanism to display in a map the location associated with assigned coordinates in the list view of all locations.  That way, after entering a lat/long value and saving it, the user can see if the lat/long coordinates make sense.

**Comment by anthonyjchriste** [comment]
Bump.

**Comment by anthonyjchriste** [comment]
Further, trying to edit a location results in displaying a blank page.

**Comment by anthonyjchriste** [comment]
Ok, the ordering for the coordinates currently is longitude followed by latitude, each in their own box.
