### ISSUE TITLE
Create a reproducible build of OPQ

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#190]
Please do work for this task in a branch called issue-190.

Currently, the process of setting up an entirely new and separate OPQ system is cumbersome. To finish this task:

- [x] Create build scripts for each OPQ service that will build a docker image for that service
- [x] Deploy docker images to public network (Docker Hub?)
- [x] Create a single install script, that assuming docker is already installed on a system, will download and install all OPQ docker images
- [x] Create a single run script that is able to bring up all docker images into a running OPQ system
- [ ] Create system level install scripts to run OPQ as a system service (init.v, systemd, etc)
- [x] Create documentation in docusaurus that documents installing, configuring, and running a new OPQ system

Please also document and create issues for road blocks you encounter along the way so we can follow the progress.

**Comment by philipmjohnson** [comment]
I think this is pretty close. If there are remaining things, we'll create new issues for them.
