### ISSUE TITLE
Create a box-config-daemon box service

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#198]
Please do work for this task in a branch called issue-198.

Currently, the box-config-daemon is started as part of init.rc. Instead, ensure that the box-config-daemon is started using systemd.

**Comment by philipmjohnson** [comment]
Hey, can you rename your branch from 198 to issue-198?  Minor thing, but will keep the branch names more consistent.

**Comment by anthonyjchriste** [comment]
I'm not seeing any branches named 198. There is a branch named issue-198 already.

**Comment by anthonyjchriste** [comment]
Did you mean to refer to branch 168 https://github.com/openpowerquality/opq/tree/168 ?

**Comment by philipmjohnson** [comment]
Whoops sorry!
