### ISSUE TITLE
Refresh OPQBoxes (1001 - 1008)

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#205]
(No git branch needed for this task.)

As of Feb 6 2019, several of the OPQBoxes are down:

![screen shot 2019-02-06 at 7 27 25 am](https://user-images.githubusercontent.com/290288/52363540-0041b080-29e7-11e9-9c99-a2d7c0d96af3.png)

In addition, their location is not necessarily accurately described in OPQView.

For this task, bring the system up to date with respect to OPQBoxes:

- [ ] Retrieve OPQBoxes from locations across campus.
- [x] Update software on deployed boxes to include new updater. 
- [x] Configure boxes to send data once per second, not six times per second.
- [x] Add new sticker to all boxes.
- [ ] Re-deploy boxes across campus in most appropriate locations for current research goals.
- [x] Update Box locations in OPQView to conform to their current physical location.
- [ ] Verify that they are All G (i.e. all Green) in OPQView.

**Comment by anthonyjchriste** [comment]
Proposed locations for thesis campus deployment: https://drive.google.com/file/d/1AMe7n7brcu5tA01VYYR5uEtq8iLzX64J/view?usp=sharing

**Comment by philipmjohnson** [comment]
Close enough.
