### ISSUE TITLE
Create a makai plugin for mongo storage.

### ISSUE THREAD

**Issue by sergey-negrashov** [openpowerquality/opq#206]
Please do work for this task in a branch called issue-206.

Create a new plugin for interfacing with mongo.
Start with the boiler plate and add functionality as needed.
1. Establish a database connection to mongo.
2. Load settings from the TriggeringService.
3. Push measurements into mongo.
4. Push trends into mongo.

**Comment by philipmjohnson** [comment]
Updated this task description to indicate that the work should be done in a branch called issue-206.
