### ISSUE TITLE
Ensure index creation for all makai/mauka related Mongo documents.

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#218]
Please do work for this task in a branch called issue-218.

Now that we've migrated to a fresh database, we need to ensure that the proper indexes are being created for each document.

These include
- [ ] measurements
- [ ] trends
- [ ] events
- [ ] incidents

We also want to make the TTL tunable for these collections per conformance with Laha.

**Comment by sergey-negrashov** [comment]
I created an expiration index on measurements
