### ISSUE TITLE
Implement detailed metrics and instrumentation for all Mauka plugins

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#220]
Please do work for this task in a branch called issue-220.

We can currently calculate the size of different collections and layers with Laha, but we're not storing this data for long term analysis.

Further, we should be able to collect metrics on how often different plugins get called and the amount of data passing from plugin to plugin within Mauka.

Implement metrics collection and analysis with something such a prometheus as a backend and grafana for display. 

Data storage metrics for:
- [x] instantaneous measurements layer
- [x] aggregate measurements layers
- [x] detentions layer
- [x] incidents layer
- [x] phenomena layer

Counts for:
- [x] measurements
- [x] trends
- [x] events
- [x] incidents
- [x] phenomena

I also want to collect detailed metrics on plugins
- [x] How many messages does each plugin receive per time window
- [x] How many messages does each plugin forward per time window
- [x] How much data does each plugin receive per message
- [x] How much data does each plugin forward per message

System metrics captured with https://github.com/giampaolo/psutil
- [x] Memory
- [x] Disk
- [x] CPU

Finally
- [ ] Document the new metric collection

**Comment by philipmjohnson** [comment]
I think Prometheus and Grafana are way overkill for your current use cases.  

I am pretty sure it will be far less trouble to learn a little React and a little less Meteor and just extend View with this functionality.  Plus, this avoids two more technology components, two more Docker containers, etc. 

It would be good to spec out all of the metrics needed for your thesis in one place so we have a good perspective on what's needed.  If things get super complicated, then maybe additional tech stack components might be warranted.

**Comment by anthonyjchriste** [comment]
Yes, a list of metrics is probably important. I will start with a high-level definition of what I want to collect and iterate from there.

For each layer in the Laha hierarchy, I want to store the total amount of data within that Layer a set interval. Say, once per minute (but this, like everything else in Laha should be configurable). 

Data storage metrics for:
- [ ] instantaneous measurements layer
- [ ] aggregate measurements layers
- [ ] detentions layer
- [ ] incidents layer
- [ ] phenomena layer

I already have code that computes these values, but I am not storing them at a specified interval to see how they change over time.

I also want to collect detailed metrics on plugins
- [ ] How many messages does each plugin receive per time window
- [ ] How many messages does each plugin forward per time window
- [ ] How much data does each plugin receive per message
- [ ] How much data does each plugin forward per message

The above metrics will provide insight on data movement not just between plugins, but also between layers that the plugins operate within.

Finally, I want to collect metrics on CPU, memory, and network utilization over time for Mauka.

**Comment by philipmjohnson** [comment]
This is a good start.  I don't see any technical reason to gather this data more frequently than once per hour, and once per day is probably good enough. I think a reasonable approach is to create a new Mongo collection called something like "MaukaMetrics" along with a timer-based process that wakes up once a day, computes these values, creates a single document, and inserts it. Some of the document fields might be objects so that they can be extended without impacting the schema.  The counts for plugins is a good example: you don't want to change the schema each time you add a new plugin.
