### ISSUE TITLE
Create a user interface for display of incidents and phenomena

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#228]
Please do work for this task in a branch called issue-228.

Currently View only displays events which may or may not contain PQ issues. Events are analyzed in Mauka to produce incidents and phenomena. These contain actual classifications of PQ issues and are intended to provide more information about PQ phenomena. 

Please add the ability to display, search, and filter incidents to View.

**Comment by aghalarp** [comment]
Incidents UI has been completed. Once Phenomena are implemented, it should be relatively straight forward to adapt the IncidentInspector and IncidentViewer components to work with the Phenomena data model.
