### ISSUE TITLE
Ignore "type" field for events in View

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#229]
Please do work for this task in a branch called issue-229.

Currently, all events are displayed with a type of "VOLTAGE_SAG". This is because View requires the type field to be populated in order to display events. 

However, we are no longer performing any classification in events. Makai does not support event types while triggering. Classification is only performed in incidents and higher. 

Please remove the display for events that show the event type. Also please allow events to be displayed if the event type field is not populated.

**Comment by aghalarp** [comment]
All instances of `Event.type` has been removed from View.
