### ISSUE TITLE
Update Makai's threshold trigger plugin to allow dynamic thresholds

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#231]
Please do work for this task in a branch called issue-231.

Thresholds are currently set statically in a configuration file and read in once when the makai plugin is loaded.

Update the plugin to dynamically retrieve these values from the database. 

This goes along with #230.

**Comment by philipmjohnson** [comment]
I think this is lower priority than getting incidents and phenomena into the UI, and providing configurability at the Incident and Phenomena level.  That's where the goodness happens.

**Comment by anthonyjchriste** [comment]
Eventually we will need this ability in makai anyway so that mauka's phenomena can tune the triggering parameters for individual boxes. 

Which raises an interesting point. We can allow users to "hand tune" triggering or allow mauka to tune triggering.
