### ISSUE TITLE
Migrate collected data to new data model

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#38]
Please do work for this task in a branch called issue-038.

Migrate current OPQ data to new standardized data model. This will likely be performed offline on a copy of the OPQ DB to ensure no data is lost and that performance isn't negatively affected on the production server.

- [x] Backup data
- [x] Move backed up data to separate machine
- [x] Perform data migration
- [x] Move new collections back to production 
- [x] Verify
- [x] Remove old data from production

**Comment by sergey-negrashov** [comment]
Could you elaborate on where I can contribute here.

**Comment by anthonyjchriste** [comment]
This is specifically for migrating the database to the new data models. If you want to help, you can see the steps outlined above in the issue. It's probably easier to perform this task locally though since the database export is going to be quite sizeable. 

I would recommend creating a few issues for updating the box to the new data format first before we worry about migrating the old data. 

Here's a link to David's updated data model . https://open-power-quality.gitbooks.io/open-power-quality-manual/content/datamodel/description.html
