### ISSUE TITLE
Implement device management interface

### ISSUE THREAD

**Issue by aghalarp** [openpowerquality/opq#4]
Please do work for this task in a branch called issue-4.

A user initially registers their device using a separate device registration interface (See Issue #6 ). 

A different user interface will be required for device management, allowing users to:
- View existing devices tied to their account
- Register new devices on their account
- Manage individual device information
  - Device label (so user doesn't have to keep track of serial numbers)
  - Device location  (zip code, so we have an approximate location on each device, while still providing a degree of privacy)
  - Device permissions
- View basic device statistics (device uptime, most recent heartbeat)

Use [Meteor-Roles](https://github.com/alanning/meteor-roles) package to manage device permissions.

**Comment by philipmjohnson** [comment]
Will redo this issue.
