### ISSUE TITLE
Security Issues w/ View

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#49]
Please do work for this task in a branch called issue-047.

The following message appears on our github homepage. 

"""
We found potential security vulnerabilities in your dependencies.

Some of the dependencies defined in your package-lock.json have known security vulnerabilities and should be updated.
"""

Please update vulnerable dependencies.

**Comment by aghalarp** [comment]
This has been resolved with issue #24, which has been merged to master now.
