### ISSUE TITLE
Figure out long term data storage policy for measurements.

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#51]
Please do work for this task in a branch called issue-051.

**Comment by sergey-negrashov** [comment]
Added daemon for storage data and expiring it after 24 hours. Need to add a filter for long term data retention.

**Comment by sergey-negrashov** [comment]
issue-51 branch contains the migrated makai

**Comment by sergey-negrashov** [comment]
We are up and running with the new measurement schema
