### ISSUE TITLE
Difference between event_start_timestamp_ms and event_end_timestamp_ms is incorrect 

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#59]
Please do work for this task in a branch called issue-059.

In the "box_events" collection, the difference between the start and end timestamps are always 150. This means I can not use these fields to calculate the duration of an event and can only do so by loading all the files and counting the samples. This takes forever.

Please fix the event_end_timestamp_ms so that is represents the time of the last sample of the waveform. If can, please update all box_events in collection.

**Comment by sergey-negrashov** [comment]
fixed in 60af55f
