### ISSUE TITLE
Not all measurement documents being populated with a 'thd' field.

### ISSUE THREAD

**Issue by aghalarp** [openpowerquality/opq#60]
Please do work for this task in a branch called issue-60.

Querying the database will reveal that almost exactly half of our measurement documents do not contain a 'thd' field - which in turn throws a very large number of errors on View since it expects this field to be present.

**Comment by aghalarp** [comment]
Upon further investigation, it seems like the culprits are boxes 1 and 4 - both of which are not creating documents with a 'thd' field. Boxes 3 and 5 seem to be working perfectly fine - all of their documents have a 'thd' field present. This perfectly explains the 1:1 ratio I initially observed of measurement documents either having a 'thd' field or not having one.

**Comment by anthonyjchriste** [comment]
If boxes 1 and 4 need updated, this is a good use case to test the updater.

**Comment by sergey-negrashov** [comment]
I am closing this issues since all is working as intended.
