### ISSUE TITLE
Create OPQCloud-In-A-Box (Virtual Box, that is)

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#65]
Please do work for this task in a branch called issue-65.

- [x] Finish developing the simulator for all the OPQ Services.
- [x] Provide a configuration file which specifies which event(s) to generate, at what interval(s)
- [x] Optional: provide "push button" for generating events on demand.
- [x] Write GitBook documentation on how to install and run the simulator, and how to have a separately running OPQView instance connect to the MongoDB instance.

**Comment by sergey-negrashov** [comment]
FYI the entirety of box software stack and Makai can run in simulator mode, so it is possible to run the entire ecosystem without a physical box. I can make a vm which implements that if you guys like. This can always be done at the fixture level instead if that's what you are looking for.

**Comment by philipmjohnson** [comment]
That's great!  Let's talk more about this.
